### ISSUE TITLE
how to search out icon quickly?

### ISSUE THREAD

**Issue by Huxpro** [LPZilva/Google-Material-Icons-for-Sketch#10]
While I can use filter to filter out the layer name, I could not coordinate the icon in artboard. Any solution about it?

**Comment by jpwain** [comment]
@Huxpro What I do is use the filter field to narrow down a layer name, then select the layer from the left side list, then use `command-2` to zoom to that layer. Here's a screencap: 

![find](https://cloud.githubusercontent.com/assets/1234304/24336787/9ea6ba7a-1249-11e7-9b2d-ced9162fc981.gif)

**Comment by LPZilva** [comment]
@Huxpro; as @jpwain wrote, that's the easiest way (that I'm aware of) to lookup for an icon. Was the question answered @Huxpro?

Btw, thanks @jpwain 👍

**Comment by LPZilva** [comment]
Problem solved.
