### ISSUE TITLE
Convert into symbols so file can be used as a Sketch Library

### ISSUE THREAD

**Issue by rayshan** [LPZilva/Google-Material-Icons-for-Sketch#12]
Thanks for your work on this! Right now there's no easy way to use the icons besides copy and paste. Is this possible?

Reference: https://www.sketchapp.com/docs/libraries/

**Comment by mattdetails** [comment]
I agree with this. RIght now, I have the file open and move icons that I want to use in my applications over to my library manually and doing a few things to them. Would be cool to be able to use sketch runner to find the icon I want and be able to populate them into my library faster.

**Comment by LPZilva** [comment]
Thanks for the feedback. I'm now working on this issue.  _(Sorry for the delay on the reply)_

**Comment by LPZilva** [comment]
This issue is now fixed. This new file needs some QA ❤️

Please, let me know if you find any issue.

**Comment by rayshan** [comment]
Thanks, swapped out a few icons, seems to work well.
