### ISSUE TITLE
New Icons version 2.2

### ISSUE THREAD

**Issue by interactivematt** [LPZilva/Google-Material-Icons-for-Sketch#2]
Hi,
I think there are new icons from Google. Version 2.2 came out last week:
[Material Design Icons](https://github.com/google/material-design-icons)

Would love to see these included on your project.

Thanks!

**Comment by LPZilva** [comment]
Thanks for the info!

Im working on it and ill upload it asap :)

**Comment by LPZilva** [comment]
Updated to new Google - Material Icons 2.2
