### ISSUE TITLE
Icons off pixel grid

### ISSUE THREAD

**Issue by jpwain** [LPZilva/Google-Material-Icons-for-Sketch#5]
The icons `File / ic_file_download` and `File / ic_file_upload` are slightly off off the pixel grid. See attached screenshot. I'll submit a PR shortly with a fix.
![screen shot 2016-02-23 at 1 09 25 pm](https://cloud.githubusercontent.com/assets/1234304/13266851/dc204280-da2e-11e5-847d-414e0eaea380.png)

**Comment by imaaronjames** [comment]
Oh boy, I wonder how many icons are off the pixel grid. If you find more and need help let me know. We can divvy up the work. Divide and conquer.

**Comment by jpwain** [comment]
I've only spotted those two; hopefully that's all :) Going to fix by grabbing fresh SVGs for both from design.google.com and replacing the Icon layers with pixel-fitted versions.

**Comment by jpwain** [comment]
@imaaronjames Looks like there's a bunch more actually! At a guess, could be the culprit of Sketch's Make Grid function. Though I'll check against a previous version to see if my moving the artboards caused it...

**Comment by imaaronjames** [comment]
@jpwain This could have also been caused when I stripped out all the masks/clipping groups.

**Comment by jpwain** [comment]
Huh, if it helps get to the bottom of things, it seems as though the misfit is only on the Y axis: icon height gets squished.

**Comment by jpwain** [comment]
@imaaronjames Did you automate stripping the masks or was all manual? Wondering if you retrace your steps there, if that might fix things faster than replacing individual icons with new SVGs.

**Comment by imaaronjames** [comment]
I think I know what is going on now. When I was removing masks/clipping groups I may have inadvertently squashed entire groups of icons by one pixel when those groups were selected (damn keyboard shortcuts). It's a simple fix. I just need a little time to get off work. I can fix it.

**Comment by jpwain** [comment]
SGTM -- thanks! I verified that the squished icons are on-grid in #2 but then fall off in #3.

**Comment by imaaronjames** [comment]
Hey-o! Pull request sent. Please review.

**Comment by jpwain** [comment]
I did a quick scan of the icons I found off-grid earlier, and LGTM!

**Comment by LPZilva** [comment]
I found some more off-grid:

* ic_system_update_alt
* ic_text_fields
* ic_dehaze
* ic_wb_incandescent
* ic_wb_iridescent
* ic_wb_sunny
* ic_notifications

Could be missing some more, but that's what i could spot :)

**Comment by jpwain** [comment]
@imaaronjames If needed I'm happy to do manual adjustment on any stragglers that don't seem to have shifted due to earlier squashing.

**Comment by imaaronjames** [comment]
@jpwain Please do. I won't be able to get to this until later tonight, so if you have some time to spend today, feel free to update the icons @LPZilva mentioned above and do another pass.

**Comment by imaaronjames** [comment]
@LPZilva will you need to merge my pull request before @jpwain can update those additional icons?

**Comment by LPZilva** [comment]
I'll merge this one and then I can update them manually :)

**Comment by imaaronjames** [comment]
Moving forward, I think we should lock all icons so that this does not happen again. What are your thoughts? @LPZilva @jpwain

**Comment by jpwain** [comment]
Locking makes it harder (extra clicks) to grab the icon you need quickly... Once things are lined up, I'm not sure what extra benefit locking might have, so seems unnecessary.

**Comment by imaaronjames** [comment]
@jpwain @LPZilva My apologies, I meant lock the icon layer inside the group. The user can still copy and paste the icon group as before. Let me know if this makes.

**Comment by LPZilva** [comment]
I see you point @imaaronjames, but the same thing will happen if you "accidentally" resize the folder. Other than that, it would be extra work just to lock the all the icons. :+1: 

Thoughs @jpwain @imaaronjames ?

**Comment by jpwain** [comment]
Ah, I understand now. The way I use Material icons is almost always with a `bounds` layer included, but I usually make some modifications to that layer (like giving it a fill for visual positioning), and Sketch's selection click-through is good enough that I don't see the benefit of locking still — you could still accidentally resize the group.

My opinion: don't lock anything.

**Comment by imaaronjames** [comment]
Cool. Figured I would throw it out there. @LPZilva @jpwain Here is another open question: Should we lock the aspect ratio of all groups? Right now they are all unlocked. Locking the aspect ratio should also help with this pixel problem. 
![screen shot 2016-02-24 at 9 14 34 am](https://cloud.githubusercontent.com/assets/4715137/13294084/3d772e74-dad7-11e5-8ddd-1f984abd9916.png)

**Comment by LPZilva** [comment]
Good point! That I agree! :100: 
I'll lock the aspect ratio in order to avoid weird resizes :smile:

**Comment by jpwain** [comment]
+1 on locking width/height!

**Comment by imaaronjames** [comment]
Huzzah! Awesome guys. @LPZilva @jpwain I look forward to syncing down the new files once it's updated.

**Comment by LPZilva** [comment]
Nice work guys! :100:
