### ISSUE TITLE
No license file in the project

### ISSUE THREAD

**Issue by 00cpxxx** [LPZilva/Google-Material-Icons-for-Sketch#7]
Hi, please add a LICENSE file to the project root so users are able to check if it is suitable for their needs.

Read more at https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license

**Comment by jpwain** [comment]
@00cpxxx Good call. See #8 .

**Comment by LPZilva** [comment]
@00cpxxx Good call.
Fixed! 👍
