### ISSUE TITLE
New icons?

### ISSUE THREAD

**Issue by jtenniswood** [LPZilva/Google-Material-Icons-for-Sketch#9]
Hi
There have been some icons added recently, it would be nice to see this icon set get updated.
Thanks

**Comment by jpwain** [comment]
@jtenniswood This is set is matched up with Google's 2.2 release from about nine months ago. It doesn't look like Google added any icons in 3.0.1.

In the Sketch file you'll see red dots indicating those icons added in the last batch:

<img width="117" alt="screen shot 2016-11-15 at 7 48 43 am" src="https://cloud.githubusercontent.com/assets/1234304/20312347/ff849028-ab07-11e6-92ce-792a8bef94bd.png">

Hope that helps!

**Comment by LPZilva** [comment]
@jtenniswood - as @jpwain mentioned, there are no new icons atm. We'll make sure to update the Sketch file as soon as something new comes out. 👍
